### ISSUE TITLE
When I went back, sometimes the navbar title and other content hiden.

### ISSUE THREAD

**Issue by ceeyang** [centrual/cordova-template-framework7-vue-webpack#115]
Sometimes, When I went back, The navbar title and other content hiden.
Just like this:

![image](https://user-images.githubusercontent.com/16550007/42442567-9986d95a-839d-11e8-82ed-5bc819a7d0ed.png)

**Comment by ceeyang** [comment]
https://im2.ezgif.com/tmp/ezgif-2-e11479f54d.gif

**Comment by caiobiodere** [comment]
@ceeyang Please check again using the new framework 7 v3 version, I just pushed these changes

**Comment by ceeyang** [comment]
I fix my problem:
`
npm install framework7@latest
npm install framework7-vue@latest
npm install framework7-icons@latest
`

replace the *main.js* and *main.vue* file with this template
the problem fixed.

thanks

close #115

**Comment by ceeyang** [comment]
I fix my problem:
`
npm install framework7@latest
npm install framework7-vue@latest
npm install framework7-icons@latest
`

replace the *main.js* and *main.vue* file with this template
the problem fixed.

thanks

close #115

**Comment by ceeyang** [comment]
I had update this framework7 version, but it still not work.

**Comment by ceeyang** [comment]
When i push two page, then back the previous page, the problem still happen.
if the child controllers count is greater than two, get back is ok.
This problem only happend when i had pushed tow pages, from second page back to first page, it happend.the first page's title and backbutton is hidend,
I am got crazy.

**Comment by ceeyang** [comment]
like this:
![image](https://user-images.githubusercontent.com/16550007/42804290-1b733024-89db-11e8-9978-7afaf1ae5787.png)

**Comment by caiobiodere** [comment]
[project.zip](https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/files/2203577/project.zip) Please use this one.

Hey @ceeyang I hope you are doing a great day, I've been testing on what did you say and everything is ok, let me know everything else.

**Comment by caiobiodere** [comment]
@ceeyang how was it?

**Comment by ceeyang** [comment]
I am sorry, I just see the message now, I am going testing this again.

**Comment by ceeyang** [comment]
I find another bug in my repository:

Sometimes when I back to home, the home page cann't navigate the another page.

If possible, there is my project repository:

https://github.com/ceeyang/PDAScanner

Account: 999999
Password: 123456

**Comment by ceeyang** [comment]
The package you sent me it's ok. I don't know what's wrong with my project.

**Comment by caiobiodere** [comment]
@ceeyang did you try using cordova instead of phonegap?

**Comment by ceeyang** [comment]
I was always use cordova to run my project.

**Comment by caiobiodere** [comment]
hey @ceeyang did you fix that (sorry for my delay)?

I was just seeing your project and looks good for me.

**Comment by ceeyang** [comment]
I don't fix it. thanks for you help.
I do't know what's wrong.

**Comment by caiobiodere** [comment]
@ceeyang could you make a video describing your problem?

**Comment by ceeyang** [comment]
@caiobiodere 
I am sorry i am too late.
https://youtu.be/uS5_Xt1WirE

In my project:
It only happed when i had logined and the first push to second page.

**Comment by ceeyang** [comment]
I do't know what's problem with my project.
Thanks for your help very much.
I decided to give up on this framework.
I do't know what's wrong. 
but, now the deadline arrived. I had chooese my project root view.
thanks so much.

**Comment by ceeyang** [comment]
@caiobiodere It's a bug with framework7, not this project
more detail:
https://github.com/framework7io/framework7/issues/1985
